/*
 * This source file was generated by the Gradle 'init' task
 */
package org.plot_four_app;

//JAVAFX DEPENDENCIES
import javafx.application.Application; //Class needed for the Application
import javafx.stage.Stage; //Class needed for window(s) of the application
import javafx.scene.image.Image;

import java.io.File;

import org.plot_four_app.AssetsManager;

public class App extends Application {
    
    AssetsManager assetsManager = new AssetsManager();

    private final double WIDTH = 1000;
	private final double HEIGHT = 500;

    private Port port = new Port(WIDTH, HEIGHT, new AssetsManager(), new Controller());

    public App() {
	}

    @Override
    public void start(Stage window) {
        window.setTitle("Plot Four");
        window.getIcons().add(assetsManager.getImage());

        window.setResizable(false);

		port.controller.port = port;
		
		window.setScene(port);
		window.show();
    }

    public static void main(String[] args) {
        launch();
    }
}
